//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignChat_Maintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class frame
    {
        public int signId { get; set; }
        public int sequenceNo { get; set; }
        public Nullable<decimal> left_0_x { get; set; }
        public Nullable<decimal> left_0_y { get; set; }
        public Nullable<decimal> left_0_z { get; set; }
        public Nullable<decimal> left_1_x { get; set; }
        public Nullable<decimal> left_1_y { get; set; }
        public Nullable<decimal> left_1_z { get; set; }
        public Nullable<decimal> left_2_x { get; set; }
        public Nullable<decimal> left_2_y { get; set; }
        public Nullable<decimal> left_2_z { get; set; }
        public Nullable<decimal> left_3_x { get; set; }
        public Nullable<decimal> left_3_y { get; set; }
        public Nullable<decimal> left_3_z { get; set; }
        public Nullable<decimal> left_4_x { get; set; }
        public Nullable<decimal> left_4_y { get; set; }
        public Nullable<decimal> left_4_z { get; set; }
        public Nullable<decimal> left_5_x { get; set; }
        public Nullable<decimal> left_5_y { get; set; }
        public Nullable<decimal> left_5_z { get; set; }
        public Nullable<decimal> left_6_x { get; set; }
        public Nullable<decimal> left_6_y { get; set; }
        public Nullable<decimal> left_6_z { get; set; }
        public Nullable<decimal> left_7_x { get; set; }
        public Nullable<decimal> left_7_y { get; set; }
        public Nullable<decimal> left_7_z { get; set; }
        public Nullable<decimal> left_8_x { get; set; }
        public Nullable<decimal> left_8_y { get; set; }
        public Nullable<decimal> left_8_z { get; set; }
        public Nullable<decimal> left_9_x { get; set; }
        public Nullable<decimal> left_9_y { get; set; }
        public Nullable<decimal> left_9_z { get; set; }
        public Nullable<decimal> left_10_x { get; set; }
        public Nullable<decimal> left_10_y { get; set; }
        public Nullable<decimal> left_10_z { get; set; }
        public Nullable<decimal> left_11_x { get; set; }
        public Nullable<decimal> left_11_y { get; set; }
        public Nullable<decimal> left_11_z { get; set; }
        public Nullable<decimal> left_12_x { get; set; }
        public Nullable<decimal> left_12_y { get; set; }
        public Nullable<decimal> left_12_z { get; set; }
        public Nullable<decimal> left_13_x { get; set; }
        public Nullable<decimal> left_13_y { get; set; }
        public Nullable<decimal> left_13_z { get; set; }
        public Nullable<decimal> left_14_x { get; set; }
        public Nullable<decimal> left_14_y { get; set; }
        public Nullable<decimal> left_14_z { get; set; }
        public Nullable<decimal> left_15_x { get; set; }
        public Nullable<decimal> left_15_y { get; set; }
        public Nullable<decimal> left_15_z { get; set; }
        public Nullable<decimal> left_16_x { get; set; }
        public Nullable<decimal> left_16_y { get; set; }
        public Nullable<decimal> left_16_z { get; set; }
        public Nullable<decimal> left_17_x { get; set; }
        public Nullable<decimal> left_17_y { get; set; }
        public Nullable<decimal> left_17_z { get; set; }
        public Nullable<decimal> left_18_x { get; set; }
        public Nullable<decimal> left_18_y { get; set; }
        public Nullable<decimal> left_18_z { get; set; }
        public Nullable<decimal> left_19_x { get; set; }
        public Nullable<decimal> left_19_y { get; set; }
        public Nullable<decimal> left_19_z { get; set; }
        public Nullable<decimal> left_20_x { get; set; }
        public Nullable<decimal> left_20_y { get; set; }
        public Nullable<decimal> left_20_z { get; set; }
        public Nullable<decimal> right_0_x { get; set; }
        public Nullable<decimal> right_0_y { get; set; }
        public Nullable<decimal> right_0_z { get; set; }
        public Nullable<decimal> right_1_x { get; set; }
        public Nullable<decimal> right_1_y { get; set; }
        public Nullable<decimal> right_1_z { get; set; }
        public Nullable<decimal> right_2_x { get; set; }
        public Nullable<decimal> right_2_y { get; set; }
        public Nullable<decimal> right_2_z { get; set; }
        public Nullable<decimal> right_3_x { get; set; }
        public Nullable<decimal> right_3_y { get; set; }
        public Nullable<decimal> right_3_z { get; set; }
        public Nullable<decimal> right_4_x { get; set; }
        public Nullable<decimal> right_4_y { get; set; }
        public Nullable<decimal> right_4_z { get; set; }
        public Nullable<decimal> right_5_x { get; set; }
        public Nullable<decimal> right_5_y { get; set; }
        public Nullable<decimal> right_5_z { get; set; }
        public Nullable<decimal> right_6_x { get; set; }
        public Nullable<decimal> right_6_y { get; set; }
        public Nullable<decimal> right_6_z { get; set; }
        public Nullable<decimal> right_7_x { get; set; }
        public Nullable<decimal> right_7_y { get; set; }
        public Nullable<decimal> right_7_z { get; set; }
        public Nullable<decimal> right_8_x { get; set; }
        public Nullable<decimal> right_8_y { get; set; }
        public Nullable<decimal> right_8_z { get; set; }
        public Nullable<decimal> right_9_x { get; set; }
        public Nullable<decimal> right_9_y { get; set; }
        public Nullable<decimal> right_9_z { get; set; }
        public Nullable<decimal> right_10_x { get; set; }
        public Nullable<decimal> right_10_y { get; set; }
        public Nullable<decimal> right_10_z { get; set; }
        public Nullable<decimal> right_11_x { get; set; }
        public Nullable<decimal> right_11_y { get; set; }
        public Nullable<decimal> right_11_z { get; set; }
        public Nullable<decimal> right_12_x { get; set; }
        public Nullable<decimal> right_12_y { get; set; }
        public Nullable<decimal> right_12_z { get; set; }
        public Nullable<decimal> right_13_x { get; set; }
        public Nullable<decimal> right_13_y { get; set; }
        public Nullable<decimal> right_13_z { get; set; }
        public Nullable<decimal> right_14_x { get; set; }
        public Nullable<decimal> right_14_y { get; set; }
        public Nullable<decimal> right_14_z { get; set; }
        public Nullable<decimal> right_15_x { get; set; }
        public Nullable<decimal> right_15_y { get; set; }
        public Nullable<decimal> right_15_z { get; set; }
        public Nullable<decimal> right_16_x { get; set; }
        public Nullable<decimal> right_16_y { get; set; }
        public Nullable<decimal> right_16_z { get; set; }
        public Nullable<decimal> right_17_x { get; set; }
        public Nullable<decimal> right_17_y { get; set; }
        public Nullable<decimal> right_17_z { get; set; }
        public Nullable<decimal> right_18_x { get; set; }
        public Nullable<decimal> right_18_y { get; set; }
        public Nullable<decimal> right_18_z { get; set; }
        public Nullable<decimal> right_19_x { get; set; }
        public Nullable<decimal> right_19_y { get; set; }
        public Nullable<decimal> right_19_z { get; set; }
        public Nullable<decimal> right_20_x { get; set; }
        public Nullable<decimal> right_20_y { get; set; }
        public Nullable<decimal> right_20_z { get; set; }
    
        public virtual sign sign { get; set; }
    }
}
