//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignChat_Maintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class signcollection
    {
        public signcollection()
        {
            this.sign = new HashSet<sign>();
        }
    
        public string collectionId { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public int organisationId { get; set; }
        public string contactPerson { get; set; }
        public string contactPersonEmail { get; set; }
        public string contactPersonTel { get; set; }
        public string contactPersonTitle { get; set; }
    
        public virtual organisation organisation { get; set; }
        public virtual ICollection<sign> sign { get; set; }
    }
}
