//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignChat_Maintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class sign
    {
        public sign()
        {
            this.frame = new HashSet<frame>();
        }
    
        public int signId { get; set; }
        public string collectionId { get; set; }
        public string meaning { get; set; }
    
        public virtual ICollection<frame> frame { get; set; }
        public virtual signcollection signcollection { get; set; }
    }
}
